/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ApMediaRouteImport } from './routes/ap-media'
import { Route as AutomobilesRouteImport } from './routes/automobiles'
import { Route as AwardsRouteImport } from './routes/awards'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as MediaRouteImport } from './routes/media'
import { Route as NominateRouteImport } from './routes/nominate'
import { Route as OperationsRouteImport } from './routes/operations'
import { Route as PublicationsRouteImport } from './routes/publications'
import { Route as SponsorshipRouteImport } from './routes/sponsorship'
import { Route as TeaserRouteImport } from './routes/teaser'
import { Route as TechnologyRouteImport } from './routes/technology'
import { Route as VieraRouteImport } from './routes/viera'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ApMediaRoute = ApMediaRouteImport.update({
  id: '/ap-media',
  path: '/ap-media',
  getParentRoute: () => rootRouteImport,
} as any)
const AutomobilesRoute = AutomobilesRouteImport.update({
  id: '/automobiles',
  path: '/automobiles',
  getParentRoute: () => rootRouteImport,
} as any)
const AwardsRoute = AwardsRouteImport.update({
  id: '/awards',
  path: '/awards',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const MediaRoute = MediaRouteImport.update({
  id: '/media',
  path: '/media',
  getParentRoute: () => rootRouteImport,
} as any)
const NominateRoute = NominateRouteImport.update({
  id: '/nominate',
  path: '/nominate',
  getParentRoute: () => rootRouteImport,
} as any)
const OperationsRoute = OperationsRouteImport.update({
  id: '/operations',
  path: '/operations',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicationsRoute = PublicationsRouteImport.update({
  id: '/publications',
  path: '/publications',
  getParentRoute: () => rootRouteImport,
} as any)
const SponsorshipRoute = SponsorshipRouteImport.update({
  id: '/sponsorship',
  path: '/sponsorship',
  getParentRoute: () => rootRouteImport,
} as any)
const TeaserRoute = TeaserRouteImport.update({
  id: '/teaser',
  path: '/teaser',
  getParentRoute: () => rootRouteImport,
} as any)
const TechnologyRoute = TechnologyRouteImport.update({
  id: '/technology',
  path: '/technology',
  getParentRoute: () => rootRouteImport,
} as any)
const VieraRoute = VieraRouteImport.update({
  id: '/viera',
  path: '/viera',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/ap-media': typeof ApMediaRoute
  '/automobiles': typeof AutomobilesRoute
  '/awards': typeof AwardsRoute
  '/contact': typeof ContactRoute
  '/media': typeof MediaRoute
  '/nominate': typeof NominateRoute
  '/operations': typeof OperationsRoute
  '/publications': typeof PublicationsRoute
  '/sponsorship': typeof SponsorshipRoute
  '/teaser': typeof TeaserRoute
  '/technology': typeof TechnologyRoute
  '/viera': typeof VieraRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/ap-media': typeof ApMediaRoute
  '/automobiles': typeof AutomobilesRoute
  '/awards': typeof AwardsRoute
  '/contact': typeof ContactRoute
  '/media': typeof MediaRoute
  '/nominate': typeof NominateRoute
  '/operations': typeof OperationsRoute
  '/publications': typeof PublicationsRoute
  '/sponsorship': typeof SponsorshipRoute
  '/teaser': typeof TeaserRoute
  '/technology': typeof TechnologyRoute
  '/viera': typeof VieraRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/ap-media': typeof ApMediaRoute
  '/automobiles': typeof AutomobilesRoute
  '/awards': typeof AwardsRoute
  '/contact': typeof ContactRoute
  '/media': typeof MediaRoute
  '/nominate': typeof NominateRoute
  '/operations': typeof OperationsRoute
  '/publications': typeof PublicationsRoute
  '/sponsorship': typeof SponsorshipRoute
  '/teaser': typeof TeaserRoute
  '/technology': typeof TechnologyRoute
  '/viera': typeof VieraRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/ap-media'
    | '/automobiles'
    | '/awards'
    | '/contact'
    | '/media'
    | '/nominate'
    | '/operations'
    | '/publications'
    | '/sponsorship'
    | '/teaser'
    | '/technology'
    | '/viera'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/ap-media'
    | '/automobiles'
    | '/awards'
    | '/contact'
    | '/media'
    | '/nominate'
    | '/operations'
    | '/publications'
    | '/sponsorship'
    | '/teaser'
    | '/technology'
    | '/viera'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/ap-media'
    | '/automobiles'
    | '/awards'
    | '/contact'
    | '/media'
    | '/nominate'
    | '/operations'
    | '/publications'
    | '/sponsorship'
    | '/teaser'
    | '/technology'
    | '/viera'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ApMediaRoute: typeof ApMediaRoute
  AutomobilesRoute: typeof AutomobilesRoute
  AwardsRoute: typeof AwardsRoute
  ContactRoute: typeof ContactRoute
  MediaRoute: typeof MediaRoute
  NominateRoute: typeof NominateRoute
  OperationsRoute: typeof OperationsRoute
  PublicationsRoute: typeof PublicationsRoute
  SponsorshipRoute: typeof SponsorshipRoute
  TeaserRoute: typeof TeaserRoute
  TechnologyRoute: typeof TechnologyRoute
  VieraRoute: typeof VieraRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ap-media': {
      id: '/ap-media'
      path: '/ap-media'
      fullPath: '/ap-media'
      preLoaderRoute: typeof ApMediaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/automobiles': {
      id: '/automobiles'
      path: '/automobiles'
      fullPath: '/automobiles'
      preLoaderRoute: typeof AutomobilesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/awards': {
      id: '/awards'
      path: '/awards'
      fullPath: '/awards'
      preLoaderRoute: typeof AwardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/media': {
      id: '/media'
      path: '/media'
      fullPath: '/media'
      preLoaderRoute: typeof MediaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nominate': {
      id: '/nominate'
      path: '/nominate'
      fullPath: '/nominate'
      preLoaderRoute: typeof NominateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/operations': {
      id: '/operations'
      path: '/operations'
      fullPath: '/operations'
      preLoaderRoute: typeof OperationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/publications': {
      id: '/publications'
      path: '/publications'
      fullPath: '/publications'
      preLoaderRoute: typeof PublicationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sponsorship': {
      id: '/sponsorship'
      path: '/sponsorship'
      fullPath: '/sponsorship'
      preLoaderRoute: typeof SponsorshipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teaser': {
      id: '/teaser'
      path: '/teaser'
      fullPath: '/teaser'
      preLoaderRoute: typeof TeaserRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/technology': {
      id: '/technology'
      path: '/technology'
      fullPath: '/technology'
      preLoaderRoute: typeof TechnologyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/viera': {
      id: '/viera'
      path: '/viera'
      fullPath: '/viera'
      preLoaderRoute: typeof VieraRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ApMediaRoute: ApMediaRoute,
  AutomobilesRoute: AutomobilesRoute,
  AwardsRoute: AwardsRoute,
  ContactRoute: ContactRoute,
  MediaRoute: MediaRoute,
  NominateRoute: NominateRoute,
  OperationsRoute: OperationsRoute,
  PublicationsRoute: PublicationsRoute,
  SponsorshipRoute: SponsorshipRoute,
  TeaserRoute: TeaserRoute,
  TechnologyRoute: TechnologyRoute,
  VieraRoute: VieraRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
