/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as ApMediaRouteImport } from './routes/ap-media'
import { Route as AutomobilesRouteImport } from './routes/automobiles'
import { Route as AwardsRouteImport } from './routes/awards'
import { Route as CeoRouteImport } from './routes/ceo'
import { Route as ChandrashekharRouteImport } from './routes/chandrashekhar'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as DirectorRouteImport } from './routes/director'
import { Route as MdRouteImport } from './routes/md'
import { Route as MediaRouteImport } from './routes/media'
import { Route as NominateRouteImport } from './routes/nominate'
import { Route as OperationsRouteImport } from './routes/operations'
import { Route as PublicationsRouteImport } from './routes/publications'
import { Route as RameshbabupasupuletiRouteImport } from './routes/rameshbabupasupuleti'
import { Route as SponsorshipRouteImport } from './routes/sponsorship'
import { Route as TeamRouteImport } from './routes/team'
import { Route as TeaserRouteImport } from './routes/teaser'
import { Route as TechnologyRouteImport } from './routes/technology'
import { Route as VieraRouteImport } from './routes/viera'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminInquiriesRouteImport } from './routes/admin.inquiries'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminNominationsRouteImport } from './routes/admin.nominations'
import { Route as AdminPaymentsRouteImport } from './routes/admin.payments'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminSponsorshipsRouteImport } from './routes/admin.sponsorships'
import { Route as NominateIndexRouteImport } from './routes/nominate.index'
import { Route as AdminInquiriesIndexRouteImport } from './routes/admin.inquiries.index'
import { Route as AdminInquiriesIdRouteImport } from './routes/admin.inquiries.$id'
import { Route as AdminNominationsIndexRouteImport } from './routes/admin.nominations.index'
import { Route as AdminNominationsIdRouteImport } from './routes/admin.nominations.$id'
import { Route as AdminPaymentsIndexRouteImport } from './routes/admin.payments.index'
import { Route as AdminPaymentsIdRouteImport } from './routes/admin.payments.$id'
import { Route as AdminSponsorshipsIndexRouteImport } from './routes/admin.sponsorships.index'
import { Route as AdminSponsorshipsIdRouteImport } from './routes/admin.sponsorships.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ApMediaRoute = ApMediaRouteImport.update({
  id: '/ap-media',
  path: '/ap-media',
  getParentRoute: () => rootRouteImport,
} as any)
const AutomobilesRoute = AutomobilesRouteImport.update({
  id: '/automobiles',
  path: '/automobiles',
  getParentRoute: () => rootRouteImport,
} as any)
const AwardsRoute = AwardsRouteImport.update({
  id: '/awards',
  path: '/awards',
  getParentRoute: () => rootRouteImport,
} as any)
const CeoRoute = CeoRouteImport.update({
  id: '/ceo',
  path: '/ceo',
  getParentRoute: () => rootRouteImport,
} as any)
const ChandrashekharRoute = ChandrashekharRouteImport.update({
  id: '/chandrashekhar',
  path: '/chandrashekhar',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const DirectorRoute = DirectorRouteImport.update({
  id: '/director',
  path: '/director',
  getParentRoute: () => rootRouteImport,
} as any)
const MdRoute = MdRouteImport.update({
  id: '/md',
  path: '/md',
  getParentRoute: () => rootRouteImport,
} as any)
const MediaRoute = MediaRouteImport.update({
  id: '/media',
  path: '/media',
  getParentRoute: () => rootRouteImport,
} as any)
const NominateRoute = NominateRouteImport.update({
  id: '/nominate',
  path: '/nominate',
  getParentRoute: () => rootRouteImport,
} as any)
const OperationsRoute = OperationsRouteImport.update({
  id: '/operations',
  path: '/operations',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicationsRoute = PublicationsRouteImport.update({
  id: '/publications',
  path: '/publications',
  getParentRoute: () => rootRouteImport,
} as any)
const RameshbabupasupuletiRoute = RameshbabupasupuletiRouteImport.update({
  id: '/rameshbabupasupuleti',
  path: '/rameshbabupasupuleti',
  getParentRoute: () => rootRouteImport,
} as any)
const SponsorshipRoute = SponsorshipRouteImport.update({
  id: '/sponsorship',
  path: '/sponsorship',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamRoute = TeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => rootRouteImport,
} as any)
const TeaserRoute = TeaserRouteImport.update({
  id: '/teaser',
  path: '/teaser',
  getParentRoute: () => rootRouteImport,
} as any)
const TechnologyRoute = TechnologyRouteImport.update({
  id: '/technology',
  path: '/technology',
  getParentRoute: () => rootRouteImport,
} as any)
const VieraRoute = VieraRouteImport.update({
  id: '/viera',
  path: '/viera',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminInquiriesRoute = AdminInquiriesRouteImport.update({
  id: '/inquiries',
  path: '/inquiries',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRoute,
} as any)
const AdminNominationsRoute = AdminNominationsRouteImport.update({
  id: '/nominations',
  path: '/nominations',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPaymentsRoute = AdminPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSponsorshipsRoute = AdminSponsorshipsRouteImport.update({
  id: '/sponsorships',
  path: '/sponsorships',
  getParentRoute: () => AdminRoute,
} as any)
const NominateIndexRoute = NominateIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => NominateRoute,
} as any)
const AdminInquiriesIndexRoute = AdminInquiriesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminInquiriesRoute,
} as any)
const AdminInquiriesIdRoute = AdminInquiriesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminInquiriesRoute,
} as any)
const AdminNominationsIndexRoute = AdminNominationsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminNominationsRoute,
} as any)
const AdminNominationsIdRoute = AdminNominationsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminNominationsRoute,
} as any)
const AdminPaymentsIndexRoute = AdminPaymentsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminPaymentsRoute,
} as any)
const AdminPaymentsIdRoute = AdminPaymentsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminPaymentsRoute,
} as any)
const AdminSponsorshipsIndexRoute = AdminSponsorshipsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminSponsorshipsRoute,
} as any)
const AdminSponsorshipsIdRoute = AdminSponsorshipsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminSponsorshipsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/ap-media': typeof ApMediaRoute
  '/automobiles': typeof AutomobilesRoute
  '/awards': typeof AwardsRoute
  '/ceo': typeof CeoRoute
  '/chandrashekhar': typeof ChandrashekharRoute
  '/contact': typeof ContactRoute
  '/director': typeof DirectorRoute
  '/md': typeof MdRoute
  '/media': typeof MediaRoute
  '/nominate': typeof NominateRouteWithChildren
  '/operations': typeof OperationsRoute
  '/publications': typeof PublicationsRoute
  '/rameshbabupasupuleti': typeof RameshbabupasupuletiRoute
  '/sponsorship': typeof SponsorshipRoute
  '/team': typeof TeamRoute
  '/teaser': typeof TeaserRoute
  '/technology': typeof TechnologyRoute
  '/viera': typeof VieraRoute
  '/admin/inquiries': typeof AdminInquiriesRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/admin/nominations': typeof AdminNominationsRouteWithChildren
  '/admin/payments': typeof AdminPaymentsRouteWithChildren
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/sponsorships': typeof AdminSponsorshipsRouteWithChildren
  '/admin/': typeof AdminIndexRoute
  '/nominate/': typeof NominateIndexRoute
  '/admin/inquiries/$id': typeof AdminInquiriesIdRoute
  '/admin/nominations/$id': typeof AdminNominationsIdRoute
  '/admin/payments/$id': typeof AdminPaymentsIdRoute
  '/admin/sponsorships/$id': typeof AdminSponsorshipsIdRoute
  '/admin/inquiries/': typeof AdminInquiriesIndexRoute
  '/admin/nominations/': typeof AdminNominationsIndexRoute
  '/admin/payments/': typeof AdminPaymentsIndexRoute
  '/admin/sponsorships/': typeof AdminSponsorshipsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/ap-media': typeof ApMediaRoute
  '/automobiles': typeof AutomobilesRoute
  '/awards': typeof AwardsRoute
  '/ceo': typeof CeoRoute
  '/chandrashekhar': typeof ChandrashekharRoute
  '/contact': typeof ContactRoute
  '/director': typeof DirectorRoute
  '/md': typeof MdRoute
  '/media': typeof MediaRoute
  '/operations': typeof OperationsRoute
  '/publications': typeof PublicationsRoute
  '/rameshbabupasupuleti': typeof RameshbabupasupuletiRoute
  '/sponsorship': typeof SponsorshipRoute
  '/team': typeof TeamRoute
  '/teaser': typeof TeaserRoute
  '/technology': typeof TechnologyRoute
  '/viera': typeof VieraRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin': typeof AdminIndexRoute
  '/nominate': typeof NominateIndexRoute
  '/admin/inquiries/$id': typeof AdminInquiriesIdRoute
  '/admin/nominations/$id': typeof AdminNominationsIdRoute
  '/admin/payments/$id': typeof AdminPaymentsIdRoute
  '/admin/sponsorships/$id': typeof AdminSponsorshipsIdRoute
  '/admin/inquiries': typeof AdminInquiriesIndexRoute
  '/admin/nominations': typeof AdminNominationsIndexRoute
  '/admin/payments': typeof AdminPaymentsIndexRoute
  '/admin/sponsorships': typeof AdminSponsorshipsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/ap-media': typeof ApMediaRoute
  '/automobiles': typeof AutomobilesRoute
  '/awards': typeof AwardsRoute
  '/ceo': typeof CeoRoute
  '/chandrashekhar': typeof ChandrashekharRoute
  '/contact': typeof ContactRoute
  '/director': typeof DirectorRoute
  '/md': typeof MdRoute
  '/media': typeof MediaRoute
  '/nominate': typeof NominateRouteWithChildren
  '/operations': typeof OperationsRoute
  '/publications': typeof PublicationsRoute
  '/rameshbabupasupuleti': typeof RameshbabupasupuletiRoute
  '/sponsorship': typeof SponsorshipRoute
  '/team': typeof TeamRoute
  '/teaser': typeof TeaserRoute
  '/technology': typeof TechnologyRoute
  '/viera': typeof VieraRoute
  '/admin/inquiries': typeof AdminInquiriesRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/admin/nominations': typeof AdminNominationsRouteWithChildren
  '/admin/payments': typeof AdminPaymentsRouteWithChildren
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/sponsorships': typeof AdminSponsorshipsRouteWithChildren
  '/admin/': typeof AdminIndexRoute
  '/nominate/': typeof NominateIndexRoute
  '/admin/inquiries/$id': typeof AdminInquiriesIdRoute
  '/admin/nominations/$id': typeof AdminNominationsIdRoute
  '/admin/payments/$id': typeof AdminPaymentsIdRoute
  '/admin/sponsorships/$id': typeof AdminSponsorshipsIdRoute
  '/admin/inquiries/': typeof AdminInquiriesIndexRoute
  '/admin/nominations/': typeof AdminNominationsIndexRoute
  '/admin/payments/': typeof AdminPaymentsIndexRoute
  '/admin/sponsorships/': typeof AdminSponsorshipsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/ap-media'
    | '/automobiles'
    | '/awards'
    | '/ceo'
    | '/chandrashekhar'
    | '/contact'
    | '/director'
    | '/md'
    | '/media'
    | '/nominate'
    | '/operations'
    | '/publications'
    | '/rameshbabupasupuleti'
    | '/sponsorship'
    | '/team'
    | '/teaser'
    | '/technology'
    | '/viera'
    | '/admin/inquiries'
    | '/admin/login'
    | '/admin/nominations'
    | '/admin/payments'
    | '/admin/settings'
    | '/admin/sponsorships'
    | '/admin/'
    | '/nominate/'
    | '/admin/inquiries/$id'
    | '/admin/nominations/$id'
    | '/admin/payments/$id'
    | '/admin/sponsorships/$id'
    | '/admin/inquiries/'
    | '/admin/nominations/'
    | '/admin/payments/'
    | '/admin/sponsorships/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/ap-media'
    | '/automobiles'
    | '/awards'
    | '/ceo'
    | '/chandrashekhar'
    | '/contact'
    | '/director'
    | '/md'
    | '/media'
    | '/operations'
    | '/publications'
    | '/rameshbabupasupuleti'
    | '/sponsorship'
    | '/team'
    | '/teaser'
    | '/technology'
    | '/viera'
    | '/admin/login'
    | '/admin/settings'
    | '/admin'
    | '/nominate'
    | '/admin/inquiries/$id'
    | '/admin/nominations/$id'
    | '/admin/payments/$id'
    | '/admin/sponsorships/$id'
    | '/admin/inquiries'
    | '/admin/nominations'
    | '/admin/payments'
    | '/admin/sponsorships'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/ap-media'
    | '/automobiles'
    | '/awards'
    | '/ceo'
    | '/chandrashekhar'
    | '/contact'
    | '/director'
    | '/md'
    | '/media'
    | '/nominate'
    | '/operations'
    | '/publications'
    | '/rameshbabupasupuleti'
    | '/sponsorship'
    | '/team'
    | '/teaser'
    | '/technology'
    | '/viera'
    | '/admin/inquiries'
    | '/admin/login'
    | '/admin/nominations'
    | '/admin/payments'
    | '/admin/settings'
    | '/admin/sponsorships'
    | '/admin/'
    | '/nominate/'
    | '/admin/inquiries/$id'
    | '/admin/nominations/$id'
    | '/admin/payments/$id'
    | '/admin/sponsorships/$id'
    | '/admin/inquiries/'
    | '/admin/nominations/'
    | '/admin/payments/'
    | '/admin/sponsorships/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  ApMediaRoute: typeof ApMediaRoute
  AutomobilesRoute: typeof AutomobilesRoute
  AwardsRoute: typeof AwardsRoute
  CeoRoute: typeof CeoRoute
  ChandrashekharRoute: typeof ChandrashekharRoute
  ContactRoute: typeof ContactRoute
  DirectorRoute: typeof DirectorRoute
  MdRoute: typeof MdRoute
  MediaRoute: typeof MediaRoute
  NominateRoute: typeof NominateRouteWithChildren
  OperationsRoute: typeof OperationsRoute
  PublicationsRoute: typeof PublicationsRoute
  RameshbabupasupuletiRoute: typeof RameshbabupasupuletiRoute
  SponsorshipRoute: typeof SponsorshipRoute
  TeamRoute: typeof TeamRoute
  TeaserRoute: typeof TeaserRoute
  TechnologyRoute: typeof TechnologyRoute
  VieraRoute: typeof VieraRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ap-media': {
      id: '/ap-media'
      path: '/ap-media'
      fullPath: '/ap-media'
      preLoaderRoute: typeof ApMediaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/automobiles': {
      id: '/automobiles'
      path: '/automobiles'
      fullPath: '/automobiles'
      preLoaderRoute: typeof AutomobilesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/awards': {
      id: '/awards'
      path: '/awards'
      fullPath: '/awards'
      preLoaderRoute: typeof AwardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ceo': {
      id: '/ceo'
      path: '/ceo'
      fullPath: '/ceo'
      preLoaderRoute: typeof CeoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chandrashekhar': {
      id: '/chandrashekhar'
      path: '/chandrashekhar'
      fullPath: '/chandrashekhar'
      preLoaderRoute: typeof ChandrashekharRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/director': {
      id: '/director'
      path: '/director'
      fullPath: '/director'
      preLoaderRoute: typeof DirectorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/md': {
      id: '/md'
      path: '/md'
      fullPath: '/md'
      preLoaderRoute: typeof MdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/media': {
      id: '/media'
      path: '/media'
      fullPath: '/media'
      preLoaderRoute: typeof MediaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nominate': {
      id: '/nominate'
      path: '/nominate'
      fullPath: '/nominate'
      preLoaderRoute: typeof NominateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/operations': {
      id: '/operations'
      path: '/operations'
      fullPath: '/operations'
      preLoaderRoute: typeof OperationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/publications': {
      id: '/publications'
      path: '/publications'
      fullPath: '/publications'
      preLoaderRoute: typeof PublicationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rameshbabupasupuleti': {
      id: '/rameshbabupasupuleti'
      path: '/rameshbabupasupuleti'
      fullPath: '/rameshbabupasupuleti'
      preLoaderRoute: typeof RameshbabupasupuletiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sponsorship': {
      id: '/sponsorship'
      path: '/sponsorship'
      fullPath: '/sponsorship'
      preLoaderRoute: typeof SponsorshipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team': {
      id: '/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof TeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teaser': {
      id: '/teaser'
      path: '/teaser'
      fullPath: '/teaser'
      preLoaderRoute: typeof TeaserRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/technology': {
      id: '/technology'
      path: '/technology'
      fullPath: '/technology'
      preLoaderRoute: typeof TechnologyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/viera': {
      id: '/viera'
      path: '/viera'
      fullPath: '/viera'
      preLoaderRoute: typeof VieraRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/inquiries': {
      id: '/admin/inquiries'
      path: '/inquiries'
      fullPath: '/admin/inquiries'
      preLoaderRoute: typeof AdminInquiriesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/nominations': {
      id: '/admin/nominations'
      path: '/nominations'
      fullPath: '/admin/nominations'
      preLoaderRoute: typeof AdminNominationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/payments': {
      id: '/admin/payments'
      path: '/payments'
      fullPath: '/admin/payments'
      preLoaderRoute: typeof AdminPaymentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/sponsorships': {
      id: '/admin/sponsorships'
      path: '/sponsorships'
      fullPath: '/admin/sponsorships'
      preLoaderRoute: typeof AdminSponsorshipsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/nominate/': {
      id: '/nominate/'
      path: '/'
      fullPath: '/nominate/'
      preLoaderRoute: typeof NominateIndexRouteImport
      parentRoute: typeof NominateRoute
    }
    '/admin/inquiries/': {
      id: '/admin/inquiries/'
      path: '/'
      fullPath: '/admin/inquiries/'
      preLoaderRoute: typeof AdminInquiriesIndexRouteImport
      parentRoute: typeof AdminInquiriesRoute
    }
    '/admin/inquiries/$id': {
      id: '/admin/inquiries/$id'
      path: '/$id'
      fullPath: '/admin/inquiries/$id'
      preLoaderRoute: typeof AdminInquiriesIdRouteImport
      parentRoute: typeof AdminInquiriesRoute
    }
    '/admin/nominations/': {
      id: '/admin/nominations/'
      path: '/'
      fullPath: '/admin/nominations/'
      preLoaderRoute: typeof AdminNominationsIndexRouteImport
      parentRoute: typeof AdminNominationsRoute
    }
    '/admin/nominations/$id': {
      id: '/admin/nominations/$id'
      path: '/$id'
      fullPath: '/admin/nominations/$id'
      preLoaderRoute: typeof AdminNominationsIdRouteImport
      parentRoute: typeof AdminNominationsRoute
    }
    '/admin/payments/': {
      id: '/admin/payments/'
      path: '/'
      fullPath: '/admin/payments/'
      preLoaderRoute: typeof AdminPaymentsIndexRouteImport
      parentRoute: typeof AdminPaymentsRoute
    }
    '/admin/payments/$id': {
      id: '/admin/payments/$id'
      path: '/$id'
      fullPath: '/admin/payments/$id'
      preLoaderRoute: typeof AdminPaymentsIdRouteImport
      parentRoute: typeof AdminPaymentsRoute
    }
    '/admin/sponsorships/': {
      id: '/admin/sponsorships/'
      path: '/'
      fullPath: '/admin/sponsorships/'
      preLoaderRoute: typeof AdminSponsorshipsIndexRouteImport
      parentRoute: typeof AdminSponsorshipsRoute
    }
    '/admin/sponsorships/$id': {
      id: '/admin/sponsorships/$id'
      path: '/$id'
      fullPath: '/admin/sponsorships/$id'
      preLoaderRoute: typeof AdminSponsorshipsIdRouteImport
      parentRoute: typeof AdminSponsorshipsRoute
    }
  }
}

interface AdminInquiriesRouteChildren {
  AdminInquiriesIdRoute: typeof AdminInquiriesIdRoute
  AdminInquiriesIndexRoute: typeof AdminInquiriesIndexRoute
}

const AdminInquiriesRouteChildren: AdminInquiriesRouteChildren = {
  AdminInquiriesIdRoute: AdminInquiriesIdRoute,
  AdminInquiriesIndexRoute: AdminInquiriesIndexRoute,
}

const AdminInquiriesRouteWithChildren = AdminInquiriesRoute._addFileChildren(
  AdminInquiriesRouteChildren,
)

interface AdminNominationsRouteChildren {
  AdminNominationsIdRoute: typeof AdminNominationsIdRoute
  AdminNominationsIndexRoute: typeof AdminNominationsIndexRoute
}

const AdminNominationsRouteChildren: AdminNominationsRouteChildren = {
  AdminNominationsIdRoute: AdminNominationsIdRoute,
  AdminNominationsIndexRoute: AdminNominationsIndexRoute,
}

const AdminNominationsRouteWithChildren =
  AdminNominationsRoute._addFileChildren(AdminNominationsRouteChildren)

interface AdminPaymentsRouteChildren {
  AdminPaymentsIdRoute: typeof AdminPaymentsIdRoute
  AdminPaymentsIndexRoute: typeof AdminPaymentsIndexRoute
}

const AdminPaymentsRouteChildren: AdminPaymentsRouteChildren = {
  AdminPaymentsIdRoute: AdminPaymentsIdRoute,
  AdminPaymentsIndexRoute: AdminPaymentsIndexRoute,
}

const AdminPaymentsRouteWithChildren = AdminPaymentsRoute._addFileChildren(
  AdminPaymentsRouteChildren,
)

interface AdminSponsorshipsRouteChildren {
  AdminSponsorshipsIdRoute: typeof AdminSponsorshipsIdRoute
  AdminSponsorshipsIndexRoute: typeof AdminSponsorshipsIndexRoute
}

const AdminSponsorshipsRouteChildren: AdminSponsorshipsRouteChildren = {
  AdminSponsorshipsIdRoute: AdminSponsorshipsIdRoute,
  AdminSponsorshipsIndexRoute: AdminSponsorshipsIndexRoute,
}

const AdminSponsorshipsRouteWithChildren =
  AdminSponsorshipsRoute._addFileChildren(AdminSponsorshipsRouteChildren)

interface AdminRouteChildren {
  AdminInquiriesRoute: typeof AdminInquiriesRouteWithChildren
  AdminLoginRoute: typeof AdminLoginRoute
  AdminNominationsRoute: typeof AdminNominationsRouteWithChildren
  AdminPaymentsRoute: typeof AdminPaymentsRouteWithChildren
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminSponsorshipsRoute: typeof AdminSponsorshipsRouteWithChildren
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminInquiriesRoute: AdminInquiriesRouteWithChildren,
  AdminLoginRoute: AdminLoginRoute,
  AdminNominationsRoute: AdminNominationsRouteWithChildren,
  AdminPaymentsRoute: AdminPaymentsRouteWithChildren,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminSponsorshipsRoute: AdminSponsorshipsRouteWithChildren,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface NominateRouteChildren {
  NominateIndexRoute: typeof NominateIndexRoute
}

const NominateRouteChildren: NominateRouteChildren = {
  NominateIndexRoute: NominateIndexRoute,
}

const NominateRouteWithChildren = NominateRoute._addFileChildren(
  NominateRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  ApMediaRoute: ApMediaRoute,
  AutomobilesRoute: AutomobilesRoute,
  AwardsRoute: AwardsRoute,
  CeoRoute: CeoRoute,
  ChandrashekharRoute: ChandrashekharRoute,
  ContactRoute: ContactRoute,
  DirectorRoute: DirectorRoute,
  MdRoute: MdRoute,
  MediaRoute: MediaRoute,
  NominateRoute: NominateRouteWithChildren,
  OperationsRoute: OperationsRoute,
  PublicationsRoute: PublicationsRoute,
  RameshbabupasupuletiRoute: RameshbabupasupuletiRoute,
  SponsorshipRoute: SponsorshipRoute,
  TeamRoute: TeamRoute,
  TeaserRoute: TeaserRoute,
  TechnologyRoute: TechnologyRoute,
  VieraRoute: VieraRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
